# Generated by Django 4.1.1 on 2022-12-07 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateTime', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('houseRules', models.TextField(default='have fun')),
                ('address', models.CharField(max_length=200)),
                ('apartment', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=5)),
                ('country', models.CharField(default='United States', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(max_length=200)),
                ('orientation', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('isHost', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='dinnerapp_other.dinner')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='dinnerapp_other.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProfile', models.BooleanField()),
                ('imgUrl', models.TextField()),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='dinnerapp_other.dinner')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='dinnerapp_other.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.profile')),
            ],
        ),
        migrations.AddField(
            model_name='dinner',
            name='attendees',
            field=models.ManyToManyField(to='dinnerapp_other.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.dinner'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.profile'),
        ),
    ]
