# Generated by Django 4.1.3 on 2022-12-05 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.TextField()),
                ('bannerImage', models.TextField()),
                ('pronouns', models.CharField(max_length=200)),
                ('orientation', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('isHost', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('location', models.TextField()),
                ('capacity', models.IntegerField()),
                ('isPublic', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.profile')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.dinner'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.profile'),
        ),
    ]
