# Generated by Django 4.1.3 on 2022-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='dinnerapp_other.profile'),
        ),
    ]
