# Generated by Django 4.1.3 on 2022-12-06 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner',
            old_name='time',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bannerImage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileImage',
        ),
        migrations.AddField(
            model_name='dinner',
            name='houseRules',
            field=models.TextField(default='have fun'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 12, 6, 20, 25, 32, 214890)),
        ),
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isHost',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='dinnerapp_other.dinner')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='dinnerapp_other.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProfile', models.BooleanField()),
                ('imgUrl', models.TextField()),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='dinnerapp_other.dinner')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='dinnerapp_other.profile')),
            ],
        ),
    ]
