# Generated by Django 4.1.4 on 2022-12-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bannerImage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileImage',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProfile', models.BooleanField()),
                ('imgUrl', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dinnerapp_other.profile')),
            ],
        ),
    ]
