# Generated by Django 4.1.3 on 2022-12-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dinnerapp_other.location'),
        ),
    ]
