# Generated by Django 4.1.1 on 2022-12-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0002_remove_profile_bannerimage_and_more'),
        ('dinnerapp_other', '0002_rename_time_dinner_datetime_rename_about_profile_bio_and_more'),
    ]

    operations = [
    ]
