# Generated by Django 4.1.1 on 2022-12-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0003_merge_20221206_2034'),
        ('dinnerapp_other', '0003_merge_20221206_2045'),
    ]

    operations = [
    ]
