# Generated by Django 4.1.3 on 2022-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0003_dinner_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='location',
        ),
        migrations.AddField(
            model_name='dinner',
            name='address',
            field=models.CharField(default='200-20 Criss St.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='apartment',
            field=models.CharField(default='200', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='city',
            field=models.CharField(default='New York', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='country',
            field=models.CharField(default='United States', max_length=200),
        ),
        migrations.AddField(
            model_name='dinner',
            name='state',
            field=models.CharField(default='New York', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='zip',
            field=models.CharField(default='11422', max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
