# Generated by Django 4.1.1 on 2022-12-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('dinnerapp_other', '0002_remove_profile_bannerimage_and_more'),
        ('dinnerapp_other', '0004_merge_20221206_2056'),
    ]

    operations = [
    ]
