# Generated by Django 4.1.3 on 2022-12-07 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0005_remove_dinner_host_dinner_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
