# Generated by Django 4.1.3 on 2022-12-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerapp_other', '0006_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
